# Generated by Django 4.2.7 on 2023-11-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='Default.jpg', upload_to='Services Image'),
        ),
    ]
